### ISSUE TITLE
训练失败： No such file or directory

### ISSUE THREAD

**Issue by cjh0613** [L-M-Sherlock/HITszQAbot#8]
运行

```
# 训练并测试：
# bert
python run.py --model bert

# ERNIE
python run.py --model ERNIE
```

分别报错：
`No such file or directory: 'HITSZQA/data/class.txt'`

`No such file or directory: 'HITSZQA/saved_dict/bert.ckpt'`

项目中没有对于上述两个文件的说明，烦请说明一下，谢谢。

**Comment by L-M-Sherlock** [comment]
请问你认真看 README 了么

![image](https://user-images.githubusercontent.com/32575846/138987659-8de7ec3c-bfa3-471d-ad11-3e9bad765e7e.png)

**Comment by L-M-Sherlock** [comment]
![image](https://user-images.githubusercontent.com/32575846/138987815-2e313251-a13b-4330-8537-f3db91fb59a0.png)

**Comment by cjh0613** [comment]
之前已经试过，两个仓库都各配置好了两套预训练模型文件，但是运行都报错如上。

我今天晚些时候再试。

**Comment by L-M-Sherlock** [comment]
奇怪了，我配的bert已经不需要class.txt文件了。

**Comment by cjh0613** [comment]
另外，

```
  File ".\Bert-Chinese-Text-Classification-Pytorch\utils.py", line 68, in __init__
    if len(batches) % self.n_batches != 0:
ZeroDivisionError: integer division or modulo by zero
```

**Comment by L-M-Sherlock** [comment]
这这报错应该是 x.Config() 那段代码的问题。

**Comment by cjh0613** [comment]
谢谢。我没看源码，随手改了下，成功训练 `bert` ，效果不错。

希望您正式修复以下两个问题：

1. ZeroDivisionError: integer division or modulo by zero
2. No such file or directory: 'HITSZQA/data/class.txt'

**Comment by L-M-Sherlock** [comment]
如果方便，你可以 pr 你的修改，我换了电脑后就没有跑过这个项目了。非常感谢！
